version: "3.8"
services:
  laravel-app:
    build: .
    ports:
      - "8888:80"
    volumes:
      - ./html/:/var/www/html/
  mysql_lamp:
    container_name: mysql_nht
    image: mysql:8
    ports:
      - "3336:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lamp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
volumes:
  db_data:    
